baseURL = "https://taraskaduk.com/"
languageCode = "en-us"
title = "Taras Kaduk"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Taras Kaduk"
enableEmoji = true
#publishDir = "posts"
disqusShortname = "taraskaduk"
#googleAnalytics = "UA-1XXXXXXX1-1"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "xcode"

# netlify.toml
[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"
[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"


[permalinks]
   posts = "/:year/:month/:day/:slug/"
   books = "/books/:slug/"

[params]
  logo = "/logo.png"
  # description ="Data Journalism in R"
  #mailchimp = "you can provide a mailchimp-link here"
  
[params.author]
  name = "Taras Kaduk"
  thumbnail = "/logo.jpg"
  description = "@taraskaduk"

[params.index]
  picture = "/userpic.jpg"
  title = "Taras Kaduk"
  #subtitle = "Shocked with your data!"
  mdtext = '''
My name is __Taras Kaduk__ [T…ê'r…ës K…ê'duk] _(Ukrainianüá∫üá¶: –¢–∞—Ä–∞—Å –ö–∞–¥—É–∫)_, and this is my website. I occasionally and irregularly write about data analytics and R language. On this site, you can find my posts and projects, as well as the list of recently given talks.

I have a full-time job _(to spare me the hassle of updating this page in the future, just head over to my [LinkedIn page](https://www.linkedin.com/in/taraskaduk), which is always up to date)_, but this blog is my personal endeavor, worked on and updated in my spare time.

I'm pretty active on Twitter under [@taraskaduk](https://twitter.com/taraskaduk). I live in Jacksonville, FL.
'''
  alertbar = false

[params.social]
  github = "taraskaduk"
  linkedin = "taraskaduk"
  twitter = "taraskaduk"
  instagram = "taraskaduk"

## Main Menu
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 100

[[menu.main]]
    name = "Posts"
    weight = 200
    identifier = "posts"
    url = "/posts"
    
[[menu.main]]
    name = "Talks"
    url = "/talks"
    weight = 300
    
# [[menu.main]]
#    name = "Book Notes"
#    url = "/books"
#    identifier = "books"
#    weight = 400
    
[[menu.main]]
    name = "Resume"
    url = "/resume"
    weight = 500
    
#[[menu.main]]
#    name = "About Me"
#    identifier = "about"
#    weight = 500
#    url = "/about"


[taxonomies]
  tag = "tags"
  category = "categories"
    
    
    