baseURL = "https://taraskaduk.com/"
languageCode = "en-us"
title = "Taras Kaduk"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "&copy; Taras Kaduk"
enableEmoji = true
publishDir = "docs"
disqusShortname = "taraskaduk"
#googleAnalytics = "UA-1XXXXXXX1-1"

[permalinks]
   posts = "/:year/:month/:day/:slug/"

[params]
  logo = "/logo.jpg"
  description ="Data Journalism in R"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "Taras Kaduk"
  thumbnail = "/logo.jpg"
  description = "@taraskaduk"

[params.index]
  picture = "/logo.jpg"
  title = "Taras Kaduk"
  subtitle = "I'm a unique placeholder. Working here and there!"
  mdtext = '''
Currently trying to get this blog running, still don't know what the blog will be about!\
**This textblock is a demonstration of the mdtext-param.**\
### This is a markdown heading
'''
  alertbar = false

[params.social]
  github = "taraskaduk"
  linkedin = "taraskaduk"
  twitter = "taraskaduk"
  instagram = "taraskaduk"

## Main Menu
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 100

[[menu.main]]
    name = "Posts"
    weight = 200
    identifier = "posts"
    url = "/posts"
    
[[menu.main]]
    name = "Talks"
    url = "/talks"
    weight = 300
    
[[menu.main]]
    name = "Resume"
    url = "/resume"
    weight = 400
    
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 500
    url = "/"