baseURL = "https://taraskaduk.com/"
languageCode = "en-us"
title = "Taras Kaduk"
theme = "pickles"

# Copyright notice. This is displayer in the footer.
copyright = "&copy; Taras Kaduk"
custom_css = "/static/css/custom.css"

[permalinks]
   posts = "/:year/:month/:day/:slug/"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "taraskaduk"
  instagram = "taraskaduk"
  github = "taraskaduk"
  linkedin = "taraskaduk"
  # Disqus shortname
  # disqus = "taraskaduk"
  # Google Analytics API key.
  ga_api_key = "UA-115954394-1"
  author = "Taras Kaduk"
  authorwebsite = "taraskaduk.com"
  avatar = "https://pbs.twimg.com/profile_images/1055225893269000192/qQbrASSV_400x400.jpg"
  contact = "https://twitter.com/taraskaduk"
  bio = "Ukrainian by birth, Seattleite by heart, Southern by the irony of fate. I analyze data in R and write about it."
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Data journalism in R"
  # Logo image. This is displayed ogp image.
  logo = "https://pbs.twimg.com/profile_images/1055225893269000192/qQbrASSV_400x400.jpg"
  favicon = "https://pbs.twimg.com/profile_images/1055225893269000192/qQbrASSV_400x400.jpg"
  description = "A datascience journal."
  twitterAuthor = "@taraskaduk"
  twitterSite = "@taraskaduk"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1


[[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 2

[[menu.main]]
    name = "Talks"
    url = "/talks"
    weight = 3


[[menu.main]]
    name = "About"
    url = "/about"
    weight = 4
    
[[menu.main]]
    name = "Resume"
    url = "/resume"
    weight = 5

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 6


# This is an interesting implementation of tree-like menu.
# Use it later, Taras!

# [[menu.main]]
#     identifier = "theme"
#     name = "/theme"
#     weight = 4
# 
# [[menu.main]]
#     parent = "theme"
#     name = "creating-a-new-theme"
#     url = "/posts/creating-a-new-theme"
#     weight = 1
# 
# [[menu.main]]
#     parent = "theme"
#     name = "migrate-from-jekyll"
#     url = "/posts/migrate-from-jekyll"
#     weight = 2



[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2019"
